### ISSUE TITLE
Function and class names are black when compiled on readthedocs

### ISSUE THREAD

**Issue by dwiddo** [MrDogeBro/sphinx_rtd_dark_mode#28]
When locally compiled, the names of functions and classes are blue as intended. But when compiled on readthedocs, the colors turn black and are difficult to read.

![Screenshot 2022-02-01 100812](https://user-images.githubusercontent.com/68785796/151949472-65537794-383f-4c53-a407-dab7fc7d98d2.png)

**Comment by vlandau** [comment]
I'm having the same issue, but it persists locally and when deploying to gh-pages after the build (via github actions) (via `make clean html`)

**Comment by Cielquan** [comment]
I have the same issue. It also applies to `click` CLI apps documented with `sphinx-click`.

![image](https://user-images.githubusercontent.com/43916661/169563575-481cb8cc-7ba5-4bbf-b2b3-a6e85b4d518f.png)

For me the local build is already black.

**Comment by dwiddo** [comment]
It may help to mention that I solved this issue by specifying sphinx-rtd-theme==0.5.2, it seems that 1.0.0 is causing the issue.

**Comment by dwiddo** [comment]
It may help to mention that I solved this issue by specifying sphinx-rtd-theme==0.5.2, it seems that 1.0.0 is causing the issue.

**Comment by photoniker** [comment]
Is there some activity regarding this issue? I still have dark class names.

**Comment by sanjacob** [comment]
I have this issue when using the theme along Breathe

**Comment by sanjacob** [comment]
Here's what I have come up with as a quick fix:

```css
html[data-theme="dark"].writer-html5 .rst-content dl[class]:not(.option-list):not(.field-list):not(.footnote):not(.citation):not(.glossary):not(.simple) .sig-name {
	color: var(--dark-text-color);
}

html[data-theme="dark"].writer-html5 .rst-content dd dl[class]:not(.option-list):not(.field-list):not(.footnote):not(.citation):not(.glossary):not(.simple) .sig-name {
	color:inherit;
}

```
YMMV
