### ISSUE TITLE
Black text on sphinx-rtd-theme with Breathe C++ autodoc

### ISSUE THREAD

**Issue by sanjacob** [MrDogeBro/sphinx_rtd_dark_mode#43]
Overall this is a great theme and I love the animation when switching light/dark themes.
Just a small issue with the api autodoc which causes class names to be black.

The specific CSS selector in the upstream `sphinx-rtd-theme` which causes this is:
```css
html.writer-html4 .rst-content dl:not(.docutils) .descclassname,html.writer-html4 .rst-content dl:not(.docutils) .descname,html.writer-html4 .rst-content dl:not(.docutils) .sig-name,html.writer-html5 .rst-content dl[class]:not(.option-list):not(.field-list):not(.footnote):not(.citation):not(.glossary):not(.simple) .descclassname,html.writer-html5 .rst-content dl[class]:not(.option-list):not(.field-list):not(.footnote):not(.citation):not(.glossary):not(.simple) .descname,html.writer-html5 .rst-content dl[class]:not(.option-list):not(.field-list):not(.footnote):not(.citation):not(.glossary):not(.simple) .sig-name{font-family:SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,Courier,monospace;color:#000}
```
